services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: furniture-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:80"
        networks:
            - furniture-network
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=furniture
            - DB_USERNAME=root
            - DB_PASSWORD=root

    mysql:
        image: mysql:8.0
        container_name: furniture-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: furniture
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - furniture-network

networks:
    furniture-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
